services:
  frontend:
    image: abelgeostan/cloud-frontend:v1
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://192.168.1.123:8088
    depends_on:
      - backend

  backend:
    image: abelgeostan/cloud-backend:v1
    ports:
      - "8088:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clouddb
      - SPRING_DATASOURCE_USERNAME=clouduser
      - SPRING_DATASOURCE_PASSWORD=cloudpass
      - JWT_SECRET=your-secret-key-here
      - FILE_UPLOAD_DIR=/uploads
    volumes:
      - uploads:/uploads
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=clouddb
      - POSTGRES_USER=clouduser
      - POSTGRES_PASSWORD=cloudpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  uploads:
  postgres_data:
